name: Java CI

on: [ push ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
          # https://github.com/actions/setup-java#supported-distributions
          java-version: '16'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots compile

      - name: Test with Maven
        run: mvn --batch-mode test
