name: Java CI

on: [ push ]

# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
      # https://github.com/actions/setup-java#supported-distributions
      #java_version: [ '8', '11', '16', '17' ]
      java_version: [ '16', ]

    name: Buld and Test for Java ${{ matrix.java_version }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots compile

      - name: Test with Maven
        run: mvn --batch-mode test
